[[dependency]]
name = "add-header"
version = "0.4.2"
description = "A cli to add headers to files"
license = "MPL-2.0"
authors = ["AmeKnite"]
repository = "https://github.com/ameknite/add-header"

[[dependency]]
name = "anstream"
version = "0.6.4"
description = "A simple cross platform library for writing colored text to a terminal."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependency]]
name = "anstyle"
version = "1.0.4"
description = "ANSI text styling"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2022 The rust-cli Developers"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependency]]
name = "anstyle-parse"
version = "0.2.2"
description = "Parse ANSI Style Escapes"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2016 Joe Wilm and individual contributors"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependency]]
name = "anstyle-query"
version = "1.0.0"
description = "Look up colored console capabilities"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/rust-cli/anstyle"

[[dependency]]
name = "anstyle-wincon"
version = "3.0.1"
description = "Styling legacy Windows terminals"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015 Josh Triplett, 2022 The rust-cli Developers"]
repository = "https://github.com/rust-cli/anstyle.git"
homepage = "https://github.com/rust-cli/anstyle"

[[dependency]]
name = "anyhow"
version = "1.0.75"
description = "Flexible concrete Error type built on std::error::Error"
license = "MIT OR Apache-2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/anyhow"

[[dependency]]
name = "argh"
version = "0.1.12"
description = "Derive-based argument parser optimized for code size"
license = "BSD-3-Clause"
notices = ["Copyright 2019 The Fuchsia Authors. All rights reserved."]
authors = [
    "Taylor Cramer <cramertj@google.com>",
    "Benjamin Brittain <bwb@google.com>",
    "Erick Tryzelaar <etryzelaar@google.com>",
]
repository = "https://github.com/google/argh"

[[dependency]]
name = "argh_derive"
version = "0.1.12"
description = "Derive-based argument parsing optimized for code size"
license = "BSD-3-Clause"
notices = ["Copyright 2019 The Fuchsia Authors. All rights reserved."]
authors = [
    "Taylor Cramer <cramertj@google.com>",
    "Benjamin Brittain <bwb@google.com>",
    "Erick Tryzelaar <etryzelaar@google.com>",
]
repository = "https://github.com/google/argh"

[[dependency]]
name = "argh_shared"
version = "0.1.12"
description = "Derive-based argument parsing optimized for code size"
license = "BSD-3-Clause"
notices = ["Copyright 2019 The Fuchsia Authors. All rights reserved."]
authors = [
    "Taylor Cramer <cramertj@google.com>",
    "Benjamin Brittain <bwb@google.com>",
    "Erick Tryzelaar <etryzelaar@google.com>",
]
repository = "https://github.com/google/argh"

[[dependency]]
name = "clap"
version = "4.4.6"
description = "A simple to use, efficient, and full-featured Command Line Argument Parser"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/clap-rs/clap"

[[dependency]]
name = "clap_builder"
version = "4.4.6"
description = "A simple to use, efficient, and full-featured Command Line Argument Parser"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015-2022 Kevin B. Knapp and Clap Contributors"]
repository = "https://github.com/clap-rs/clap"

[[dependency]]
name = "clap_derive"
version = "4.4.2"
description = "Parse command line argument by defining a struct, derive crate."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015-2022 Kevin B. Knapp and Clap Contributors"]
repository = "https://github.com/clap-rs/clap/tree/master/clap_derive"

[[dependency]]
name = "clap_lex"
version = "0.5.1"
description = "Minimal, flexible command line parser"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015-2022 Kevin B. Knapp and Clap Contributors"]
repository = "https://github.com/clap-rs/clap/tree/master/clap_lex"

[[dependency]]
name = "colorchoice"
version = "1.0.0"
description = "Global override of color control"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Individual contributors"]
repository = "https://github.com/rust-cli/anstyle"

[[dependency]]
name = "heck"
version = "0.4.1"
description = "heck is a case conversion library."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015 The Rust Project Developers"]
authors = ["Without Boats <woboats@gmail.com>"]
repository = "https://github.com/withoutboats/heck"

[[dependency]]
name = "proc-macro2"
version = "1.0.67"
description = "A substitute implementation of the compiler's `proc_macro` API to decouple token-based libraries from the procedural macro use case."
license = "MIT OR Apache-2.0"
authors = [
    "David Tolnay <dtolnay@gmail.com>",
    "Alex Crichton <alex@alexcrichton.com>",
]
repository = "https://github.com/dtolnay/proc-macro2"

[[dependency]]
name = "quote"
version = "1.0.33"
description = "Quasi-quoting macro quote!(...)"
license = "MIT OR Apache-2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/quote"

[[dependency]]
name = "same-file"
version = "1.0.6"
description = """
A simple crate for determining whether two file paths point to the same file.
"""
license = "Unlicense/MIT"
notices = ["Copyright (c) 2017 Andrew Gallant"]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
repository = "https://github.com/BurntSushi/same-file"

[[dependency]]
name = "serde"
version = "1.0.188"
description = "A generic serialization/deserialization framework"
license = "MIT OR Apache-2.0"
authors = [
    "Erick Tryzelaar <erick.tryzelaar@gmail.com>",
    "David Tolnay <dtolnay@gmail.com>",
]
repository = "https://github.com/serde-rs/serde"
homepage = "https://serde.rs"

[[dependency]]
name = "serde_derive"
version = "1.0.188"
description = "Macros 1.1 implementation of #[derive(Serialize, Deserialize)]"
license = "MIT OR Apache-2.0"
authors = [
    "Erick Tryzelaar <erick.tryzelaar@gmail.com>",
    "David Tolnay <dtolnay@gmail.com>",
]
repository = "https://github.com/serde-rs/serde"
homepage = "https://serde.rs"

[[dependency]]
name = "strsim"
version = "0.10.0"
description = """
Implementations of string similarity metrics. Includes Hamming, Levenshtein,
OSA, Damerau-Levenshtein, Jaro, Jaro-Winkler, and Sørensen-Dice.
"""
license = "MIT"
notices = [
    "Copyright (c) 2015 Danny Guo",
    "Copyright (c) 2016 Titus Wormer <tituswormer@gmail.com>",
    "Copyright (c) 2018 Akash Kurdekar",
]
authors = ["Danny Guo <danny@dannyguo.com>"]
repository = "https://github.com/dguo/strsim-rs"

[[dependency]]
name = "syn"
version = "2.0.37"
description = "Parser for Rust source code"
license = "MIT OR Apache-2.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/syn"

[[dependency]]
name = "unicode-ident"
version = "1.0.12"
description = "Determine whether characters have the XID_Start or XID_Continue properties according to Unicode Standard Annex #31"
license = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
notices = ["Copyright © 1991-2022 Unicode, Inc. All rights reserved."]
authors = ["David Tolnay <dtolnay@gmail.com>"]
repository = "https://github.com/dtolnay/unicode-ident"

[[dependency]]
name = "utf8parse"
version = "0.2.1"
description = "Table-driven UTF-8 parser"
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2016 Joe Wilm"]
authors = [
    "Joe Wilm <joe@jwilm.com>",
    "Christian Duerr <contact@christianduerr.com>",
]
repository = "https://github.com/alacritty/vte"

[[dependency]]
name = "walkdir"
version = "2.4.0"
description = "Recursively walk a directory."
license = "Unlicense/MIT"
notices = ["Copyright (c) 2015 Andrew Gallant"]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
repository = "https://github.com/BurntSushi/walkdir"

[[dependency]]
name = "winapi"
version = "0.3.9"
description = "Raw FFI bindings for all of Windows API."
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2015-2018 The winapi-rs Developers"]
authors = ["Peter Atashian <retep998@gmail.com>"]
repository = "https://github.com/retep998/winapi-rs"

[[dependency]]
name = "winapi-i686-pc-windows-gnu"
version = "0.4.0"
description = "Import libraries for the i686-pc-windows-gnu target. Please don't use this crate directly, depend on winapi instead."
license = "MIT/Apache-2.0"
authors = ["Peter Atashian <retep998@gmail.com>"]
repository = "https://github.com/retep998/winapi-rs"

[[dependency]]
name = "winapi-util"
version = "0.1.6"
description = "A dumping ground for high level safe wrappers over winapi."
license = "Unlicense/MIT"
notices = ["Copyright (c) 2017 Andrew Gallant"]
authors = ["Andrew Gallant <jamslam@gmail.com>"]
repository = "https://github.com/BurntSushi/winapi-util"

[[dependency]]
name = "winapi-x86_64-pc-windows-gnu"
version = "0.4.0"
description = "Import libraries for the x86_64-pc-windows-gnu target. Please don't use this crate directly, depend on winapi instead."
license = "MIT/Apache-2.0"
authors = ["Peter Atashian <retep998@gmail.com>"]
repository = "https://github.com/retep998/winapi-rs"

[[dependency]]
name = "windows-sys"
version = "0.48.0"
description = "Rust for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows-targets"
version = "0.48.5"
description = "Import libs for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows_aarch64_gnullvm"
version = "0.48.5"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows_aarch64_msvc"
version = "0.48.5"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows_i686_gnu"
version = "0.48.5"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows_i686_msvc"
version = "0.48.5"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows_x86_64_gnu"
version = "0.48.5"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows_x86_64_gnullvm"
version = "0.48.5"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"

[[dependency]]
name = "windows_x86_64_msvc"
version = "0.48.5"
description = "Import lib for Windows"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) Microsoft Corporation."]
authors = ["Microsoft"]
repository = "https://github.com/microsoft/windows-rs"
